version: "3"
services:
  steambuddydb:
    hostname: steambuddyDb
    image: mysql:5.7
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=steambuddy_db
    volumes:
      - mysql_data:/var/lib/mysql

  steambuddyapp:
    hostname: steambuddyapp
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - steambuddydb
    #entrypoint: java -jar -Dspring.profiles.active=prod steambuddy.jar

  steambuddy_web:
    # image: pjochum/steambuddyweb:latest
    build: ../web/
    ports:
      - "8081:80"
    environment:
      - STEAMBUDDY_API_URL=http://localhost:8080/internal/api/games
    depends_on:
      - steambuddyapp

volumes:
  mysql_data: