# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build ASE Backend

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./steambuddy-parent
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11.0.6
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.6
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DallowSnapshots=true
        working-directory: ${{env.working-directory}}
