# ----------------------------------------------------------------------------------------------------------------------
# GENERAL
# ----------------------------------------------------------------------------------------------------------------------
spring.application:
  name: steambuddy

spring.jpa:
  hibernate:
    ddl-auto: update 
  dialect: org.hibernate.dialect.MySQL5Dialect