# ----------------------------------------------------------------------------------------------------------------------
# GENERAL
# ----------------------------------------------------------------------------------------------------------------------
spring.application:
  name: steambuddy

spring.jpa:
  hibernate:
    ddl-auto: update 