# ----------------------------------------------------------------------------------------------------------------------
# GENERAL
# ----------------------------------------------------------------------------------------------------------------------
spring.application:
  name: steambuddy

spring.datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3310/steambuddy_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  username: root
  password: root
  platform: mysql
  initialization-mode: always
 
spring.jpa:
  hibernate:
    ddl-auto: update 